### ISSUE TITLE
AttributeError: 'COCO_dataset_generator' object has no attribute 'r_x'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#10]
```
Traceback (most recent call last):
  File "/home/usr/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "segment.py", line 332, in onclick_release
    elif self.r_x and np.abs(event.xdata - self.r_x)>10 and np.abs(event.ydata - self.r_y)>10: # 10 pixels limit for rectangle creation
AttributeError: 'COCO_dataset_generator' object has no attribute 'r_x'

```

When clicked, this is printed from time to image.

**Comment by hanskrupakar** [comment]
This error was caused because of out-of-screen or illegal clicks resulting in None objects. I added a fix with the latest commit. Apologies for the delay, I've been focused on other things. Let me know if you still get the error.
